### ISSUE TITLE
Fill summary IDS

### ISSUE THREAD

**Issue by SimonPinches** [transp/transp-imas-translator#2]
At present only the `equilibrium`, `core_profiles` and `core_transport` IDSs are filled by the TRANS-IMAS Translator. It would be good if the `summary` IDS was also filled since this could then be used for filtering in the future.

The variable `equilibrium.time_slice(itime)/global_quantities/magnetic_axis/b_field_tor` is also not filled either, hence we don't know the magnetic field of translated simulations either. Could you please modify the translator to fill this quantity as well?

Thanks.

See original JIRA issue raised by Mireille here: [IMAS-1050](https://jira.iter.org/browse/IMAS-1050)

**Comment by MireilleSchneider** [comment]
I just subscribed. How is it that there is no assignee for this tracker?

**Comment by MireilleSchneider** [comment]
When there are more than one ion, let's say 2 ions, the quantities core_profiles.profiles_1d{1}.ion{1}.element{1}.a and z_n are correctly filled, but the quantities core_profiles.profiles_1d{1}.ion{2}.element{1}.a and z_n are not filled at all. Could you please complete the filling of the plasma composition in core_profiles?
