### ISSUE TITLE
Add `core sources` IDS

### ISSUE THREAD

**Issue by orso82** [transp/transp-imas-translator#3]
To perform any transport analysis off of the TRANSP data stored in IMAS requires that the `core_sources` IDS to be populated.

If it helps, I have found a METIS simulation in the ITER scenario database:
```
-------------------------------------------------------------------------------------------------
Machine  Pulse   Run  Reference                   Ip[MA]  B0[T]  Fuelling  Confinement  Workflow
-------------------------------------------------------------------------------------------------
ITER     130010  1    ITER-steady-state-DT         9.0    5.3    D-T       L-H          METIS
```
that has that IDS filled.

**Comment by transp** [comment]
A core_sources IDS is now being populated with TRANSP output data for EC, IC and NBI. Example output for TRANSP run 38530B17 can be found in /home/ITER/carlssj/public/imasdb/imas_trees/0

The code works when linked w/ v. 3.7.0 of the IMAS library, which must be compiled with -O0. Note that the 3.7.0 documentation does not match the source code (for example, core_sources%source%global_quantities and momentum sources are not implemented).

**Comment by SimonPinches** [comment]
Just a remark that the IDSs produced by METIS are being updated as a result of corrections to conform to the ITER coordinates/definitions (COCOS=11).
