### ISSUE TITLE
The number of radial points is different between the TRANSP run and the data stored in IMAS

### ISSUE THREAD

**Issue by orso82** [transp/transp-imas-translator#4]
Not sure if this is a bug or a feature, but I would have expected the number of points to match between the data stored in IMAS and the TRANSP statefile

**Comment by transp** [comment]
I don't know if it's a feature, but at least it's not a bug! The TRANSP XB variable is the zone boundaries (flux surfaces), excluding the magnetic axis! On-axis quantities in TRANSP are stored in separate variables from the profile arrays. IMAS arrays include the axis and therefore have one more radial point.
